'use strict';

let listaProveedores = [{
    'nombre': 'Allan Campos',
    'tel': '87736412',
    'id': 'fisica',
    'cedula': '208090801',
    'correo': 'acampos@gmail.com',
    'sexo': 'Masculino',
    'tipo': 'Veterinaria',
    'direccion': 'Estancias latinas, San Pedro, Montes de Oca',
    'fecha': '20-04-2017',
}, {
    'nombre': 'Francisco Arguedas',
    'tel': '87736412',
    'id': 'dimex',
    'cedula': '109790801',
    'correo': 'acampos@gmail.com',
    'sexo': 'Masculino',
    'tipo': 'Postres',
    'direccion': 'Estancias latinas, San Pedro, Montes de Oca',
    'fecha': '20-04-2017',
}, {
    'nombre': 'Mariel Cascante',
    'tel': '87736412',
    'id': 'dimex',
    'cedula': '111022801',
    'correo': 'marielcc@gmail.com',
    'sexo': 'Femenino',
    'tipo': 'Hotel',
    'direccion': 'Estancias latinas, San Pedro, Montes de Oca',
    'fecha': '20-04-2017',
}, {
    'nombre': 'Nathan Mohamed',
    'tel': '87736412',
    'id': 'fisica',
    'cedula': '203320222',
    'correo': 'acampos@gmail.com',
    'sexo': 'Masculino',
    'tipo': 'Estetica',
    'direccion': 'Barrio Lourdes, Ciudad Quesada, Alajuela',
    'fecha': '20-04-2016',
}, {
    'nombre': 'Roberto Villalobos',
    'tel': '87736412',
    'id': 'dimex',
    'cedula': '204040801',
    'correo': 'acampos@gmail.com',
    'sexo': 'Masculino',
    'tipo': 'Paseador',
    'direccion': 'Barrio El Campo, Ciudad Quesada, Alajuela',
    'fecha': '20-04-2019',
}, {
    'nombre': 'Esteban Vega',
    'tel': '87736412',
    'id': 'fisica',
    'cedula': '208012501',
    'correo': 'acampos@gmail.com',
    'sexo': 'Masculino',
    'tipo': 'Veterinaria',
    'direccion': 'Estancias latinas, San Pedro, Montes de Oca',
    'fecha': '20-04-2018',
}];